# Keras regression assignment
## by Matan Weissbuch

importing all necessary libraries

In [8]:
import numpy as np
import pandas as pd
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

load concrete data csv file from folder

In [9]:
df = pd.read_csv('concrete_data.csv')
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

split data to prediction and target, or to independent variables (X) and dependent variable (y)

In [10]:
x = df[['Cement',
        'Blast Furnace Slag',
        'Fly Ash',
        'Water', 
        'Superplasticizer',
        'Coarse Aggregate', 
        'Fine Aggregate',
        'Age']]

y = df[['Strength']]

define the function for creating the neural network, using the network properties as defined in the assignment instructions

In [11]:
# define regression model
def regression_model(n_cols):
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

normalize the data - subtract X values from the mean, and divide by the std

In [12]:
x_norm = (x - x.mean()) / x.std()

x_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

train and test the neural network for 50 times, and keep the MSE results for each training
generate the test and train set of X (independent variables) from the normalized data. this time, we run the training with 100 epochs

In [13]:
n_split_iter = 50
mse = np.zeros(n_split_iter)

for i in range(n_split_iter):
    X_train, X_test, y_train, y_test = train_test_split(
    x_norm, 
    y, 
    test_size=0.3, 
    random_state=4)

    print ('Train set:', X_train.shape,  y_train.shape)
    print ('Test set:', X_test.shape,  y_test.shape)

    model = regression_model(8)
    model.fit(X_train, y_train, epochs=50, verbose=0)
    
    yhat = model.predict(X_test)
    
    v = np.mean((yhat - y_test) ** 2)
    mse[i] = v
    print("MSE %.2f" % v)

Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 15ms/step
MSE 146.46
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 19ms/step
MSE 149.99
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 13ms/step
MSE 95.65
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 12ms/step
MSE 146.61
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 12ms/step
MSE 116.75
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 15ms/step
MSE 132.88
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 15ms/step
MSE 147.66
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 16ms/step
MSE 149.87
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 17ms/step
MSE 143.83
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 11ms/step
MSE 149.20
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 11ms/step
MSE 152.28
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 13ms/step
MSE 141.82
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 22ms/step
MSE 144.53
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 16ms/step
MSE 146.13
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 17ms/step
MSE 144.01
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 9ms/step
MSE 137.90
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 20ms/step
MSE 150.80
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 15ms/step
MSE 141.07
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 14ms/step
MSE 99.65
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 15ms/step
MSE 155.22
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 16ms/step
MSE 151.87
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 9ms/step
MSE 135.45
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 11ms/step
MSE 144.14
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 11ms/step
MSE 143.09
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 10ms/step
MSE 152.14
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 17ms/step
MSE 118.85
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 14ms/step
MSE 116.81
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 14ms/step
MSE 139.39
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 11ms/step
MSE 147.07
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 13ms/step
MSE 150.77
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 7ms/step
MSE 150.43
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 21ms/step
MSE 127.25
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 16ms/step
MSE 145.32
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 12ms/step
MSE 136.50
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 13ms/step
MSE 148.40
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 11ms/step
MSE 125.03
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 14ms/step
MSE 129.39
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 16ms/step
MSE 121.06
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 10ms/step
MSE 152.44
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 14ms/step
MSE 106.57
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 10ms/step
MSE 127.95
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 12ms/step
MSE 112.38
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 15ms/step
MSE 139.32
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 11ms/step
MSE 144.31
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 9ms/step
MSE 149.76
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 16ms/step
MSE 151.30
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 16ms/step
MSE 147.09
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 15ms/step
MSE 151.42
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 21ms/step
MSE 137.58
Train set: (721, 8) (721, 1)
Test set: (309, 8) (309, 1)
10/10 [==============================] - 0s 18ms/step
MSE 154.74

analysis of the MSE

In [14]:
mse_mean = np.mean(mse)
mse_std = np.std(mse)

print("MSE mean: %.2f" % mse_mean)
print("MSE std: %.2f" % mse_std)

MSE mean: 139.00
MSE std: 14.53